- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3  # Versi terbaru
  with:
    host: ${{ secrets.EC2_HOST }}          # IP address EC2
    username: ${{ secrets.EC2_USER }}      # Username untuk SSH
    key: ${{ secrets.EC2_SSH_KEY }}        # Private key
    port: ${{ secrets.EC2_PORT }}          # SSH port (default 22)
    script: |                              # Script yang akan dijalankan di EC2
      echo "Hello from GitHub Actions!"
      cd /path/to/your/project
      git pull origin main
      npm install
      pm2 restart myapp
