- name: Deploy to Amazon Linux EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.AWS_HOST }}
    username: ec2-user
    key: ${{ secrets.AWS_KEY }}
    script: |
      cd ~/ci-cd-github-node.js
      git pull origin main
      npm install
      pm2 restart myapp || pm2 start index.js --name myapp
