  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
        uses: actions/checkout@v3

       - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ci-cd-github-node.js
            git pull origin main
            npm install
            pm2 start ecosystem.config.js
