name: Telegram Notification
on:
  deployment_status  

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Alert
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}  
          to: ${{ secrets.TELEGRAM_CHAT_ID }}   
          message: |
            🚀 Deployment Update:
            Status: ${{ github.event.deployment_status.state }}
            Repo: ${{ github.repository }}
            URL: ${{ github.event.deployment_status.target_url }}
            Commit: ${{ github.sha }}
